MSG_NEW_USER = "new user|{number}|{name}|{department}"
MSG_UPDATE_PASSWORD = "update password|{name}"
MSG_UPDATE_DEPARTMENT = "update department|{name}|{department}"
EMPLOYEE_USER_TOPIC = "employee-user"
USER_TASK_TOPIC = "user-task"
